services:
  service-registry:
    image: serviceregistry:latest
    container_name: serviceregistry
    working_dir: /app
    volumes:
      - ./ServiceRegistry/target/ServiceRegistry-0.0.1-SNAPSHOT.jar:/app/ServiceRegistry-0.0.1-SNAPSHOT.jar
    ports:
      - "8761:8761"
    entrypoint: ["java", "-jar", "ServiceRegistry-0.0.1-SNAPSHOT.jar"]
    networks:
      - microservices-net

  user-service:
    image: userservice:latest
    container_name: userservice
    working_dir: /app
    volumes:
      - ./UserService/target/UserService-0.0.1-SNAPSHOT.jar:/app/UserService-0.0.1-SNAPSHOT.jar
    ports:
      - "9001:9001"
    entrypoint: ["java", "-jar", "UserService-0.0.1-SNAPSHOT.jar"]
    environment:
      - CLOUDINARY_CLOUD_NAME=dctoqfkw0
      - CLOUDINARY_API_KEY=951526354525734
      - CLOUDINARY_API_SECRET=0YOP7Q-AasOxPHuE7O5w-A5Hwhw
      - SPRING_DATA_MONGODB_URI=mongodb+srv://nishantrathore2002:rootuser@projectdatabase.ih0yz.mongodb.net/?retryWrites=true&w=majority&appName=ProjectDatabase
      - SPRING_DATA_MONGODB_DATABASE=userService
      - JWT_SECRET=TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=2MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=2MB
    networks:
      - microservices-net

  doctor-service:
    image: doctorservice:latest
    container_name: doctorservice
    working_dir: /app
    volumes:
      - ./DoctorService/target/DoctorService-0.0.1-SNAPSHOT.jar:/app/DoctorService-0.0.1-SNAPSHOT.jar
    ports:
      - "9002:9002"
    entrypoint: ["java", "-jar", "DoctorService-0.0.1-SNAPSHOT.jar"]
    environment:
      - CLOUDINARY_CLOUD_NAME=dctoqfkw0
      - CLOUDINARY_API_KEY=951526354525734
      - CLOUDINARY_API_SECRET=0YOP7Q-AasOxPHuE7O5w-A5Hwhw
      - SPRING_DATA_MONGODB_URI=mongodb+srv://nishantrathore2002:rootuser@projectdatabase.ih0yz.mongodb.net/?retryWrites=true&w=majority&appName=ProjectDatabase
      - SPRING_DATA_MONGODB_DATABASE=doctorService
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=2MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=2MB
    networks:
      - microservices-net

  appointment-service:
    image: appointmentservice:latest
    container_name: appointmentservice
    working_dir: /app
    volumes:
      - ./AppointmentService/target/AppointmentService-0.0.1-SNAPSHOT.jar:/app/AppointmentService-0.0.1-SNAPSHOT.jar
    ports:
      - "9003:9003"
    entrypoint: ["java", "-jar", "AppointmentService-0.0.1-SNAPSHOT.jar"]
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://nishantrathore2002:rootuser@projectdatabase.ih0yz.mongodb.net/?retryWrites=true&w=majority&appName=ProjectDatabase
      - SPRING_DATA_MONGODB_DATABASE=appointmentService
      - RZP_KEY_ID=your_razorpay_key_id
      - RZP_KEY_SECRET=your_razorpay_key_secret
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge